model_params:
  iterations: 1024
  learning_rate: 0.06
  depth: 10
  eval_metric: "TotalF1:average=Macro"
  early_stopping_rounds: 50
  verbose: 30
  subsample: 0.8
  random_state: 42
  task_type: "CPU"

target_column: "target"
save_model_path: "./models/model.cbm"